### ISSUE TITLE
[feat]: Shared API

### ISSUE THREAD

**Issue by cjeongmin** [capstone-maru/maru-front-end#46]
## Overview

Shared 도메인의 API를 이용해서 해당 기능을 구현합니다.

## Tasks

- [x] 방 있는 메이트 게시판 목록 조회
- [x] 방 있는 메이트 게시글 작성
- [x] 방 있는 메이트 단일 게시글 조회
- [x] 방 있는 메이트 게시글 삭제
- [x] 방 있는 메이트 게시글 스크랩
