### ISSUE TITLE
[Fix]: Apply changes to the Shared API

### ISSUE THREAD

**Issue by cjeongmin** [capstone-maru/maru-front-end#75]
## Overview

Shared 도메인의 API 변경 사항 적용.

## Tasks

- [x] GET /shared/posts/dormitory
- [x] POST /shared/posts/dormitory
- [x] GET /shared/posts/dormitory/{postId}
- [x] PUT /shared/posts/dormitory/{postId}
- [x] DELETE /shared/posts/dormitory/{postId}
- [x] POST /shared/posts/dormitory/{postId}/scrap
- [x] GET /shared/posts/studio
- [x] GET /shared/posts/studio/{postId}
- [x] PUT /shared/posts/studio/{postId}
